---
- hosts: tomcat
  become: true
  tasks:
    - name: copy war file
      copy:
        src: /var/lib/jenkins/workspace/maven-build/target/myapp.war
        dest: /home/ec2-user/apache-tomcat-8.5.82/webapps
