---
- hosts: tomcat
  tasks:
    - name: copy war file
      copy:
        src: /var/lib/jenkins/workspace/maven-build/target/myapp.war
        dest: /home/ec2-user/apache-tomcat-8.5.82/webapps
    - name: start server
      copy:
        src: script.sh
        dest: /home/ec2-user/script.sh
        mode: '0777'
    - name: run server
      command: "sh /home/ec2-user/script.sh"
