---
- hosts: tomcat
  tasks:
    - name: copy war file
      copy:
        src: /var/lib/jenkins/workspace/maven-build/target/myapp.war
        dest: /home/ec2-user/apache-tomcat-8.5.82/webapps
    - name: shutdown server
      shell: "/home/ec2-user/apache-tomcat-8.5.82/bin/shutdown.sh"
    - name: start server
      shell: "/home/ec2-user/apache-tomcat-8.5.82/bin/startup.sh"
