---
 - hosts: all
   become: true
   tasks:
     - name: Installing Packages
       yum:
         name: ['git','docker','httpd','java-1.8.0-openjdk-devel']
         state: present
     - name: Starting Docker and Httpd
       yum:
         name: "{{item}}"
         state: present
       with_items:
         - docker
         - httpd
